### ISSUE TITLE
Missing component `v-textarea`

### ISSUE THREAD

**Issue by crutchcorn** [vuetifyjs/api-generator#4]
Although I may have missed something, I seem to notice a component missing from the generator. This is the textarea component documented here:
https://vuetifyjs.com/en/components/textarea

**Comment by BenRichter** [comment]
"v-textarea" is available in _fakeComponents .js_ and _.ts_. PhpStorm has no problem finding the Item and its corresponding props. 
@crutchcorn Is this still a problem?

**Comment by jacekkarczmarczyk** [comment]
`textarea` component is now visible in docs. 
At the moment we're adding components manually on a la carte page, so it doesn't use api generator and has nothing to do with _fakeComponents_, but definitely it should be done automatically, I've created an issue in docs repo https://github.com/vuetifyjs/vuetifyjs.com/issues/612
